# Generated by Django 4.2.2 on 2023-06-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
