# Generated by Django 4.2.2 on 2023-06-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0002_alter_producto_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caducacion',
            field=models.DateField(verbose_name='LA REAL FECHA'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='CODIFICACION'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
